/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.projeto.webservice.producer.service;

import java.util.Set;
import javax.ws.rs.core.Application;

@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.br.projeto.webservice.producer.service.UserprojFacadeREST.class);
        resources.add(com.br.projeto.webservice.producer.service.PlaceFacadeREST.class);        
        resources.add(com.br.projeto.webservice.producer.service.DirectoryFacadeREST.class);
        resources.add(com.br.projeto.webservice.producer.service.PlaceFacadeREST.class);
        resources.add(com.br.projeto.webservice.producer.service.UserinfoFacadeREST.class);
        resources.add(com.br.projeto.webservice.producer.service.UserprojFacadeREST.class);
        resources.add(com.br.projeto.webservice.producer.service.UsertypeFacadeREST.class);        
    }
    
}